#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=3

# ── Config ────────────────────────────────────────────────────────────────
# contextId identifies the Tripletex company (Capra Consulting AS). Tripletex
# 404s without it, so it is not optional.
CONTEXT_ID="${TRIPLETEX_CONTEXT_ID:-228265}"
BASE="https://tripletex.no/execute"
MONTH_URL="$BASE/monthlyHourlist?contextId=$CONTEXT_ID"   # Månedsoversikt
LOGIN_URL="$BASE/login"

# Month to display: first arg as YYYY-MM, else the current month.
TARGET_MONTH="${1:-$(date +%Y-%m)}"
if [[ ! "$TARGET_MONTH" =~ ^[0-9]{4}-[0-9]{2}$ ]]; then
  printf 'usage: %s [YYYY-MM]\n' "$0" >&2
  exit 2
fi

PW_SESSION=""
TMPJS=""
trap '[[ -n "$TMPJS" ]] && rm -f "$TMPJS"' EXIT

# run_js '<json>' <<'JS' ... JS. Runs JS in the playwriter sandbox with `CFG`
# pre-bound to the JSON you pass. Keeps bash values out of the JS entirely, so
# nothing has to be escaped through two layers of quoting.
run_js() {
  { printf 'const CFG = %s;\n' "$1"; cat; } > "$TMPJS"
  playwriter -s "$PW_SESSION" --timeout "${PW_TIMEOUT:-120000}" -f "$TMPJS" 2>&1
}

# Is there a live Tripletex session? Prints VERDICT=live or VERDICT=login.
check_session() {
  run_js "{\"url\":\"$MONTH_URL\"}" <<'JS'
let verdict = 'login'
try {
  if (!state.page || state.page.isClosed()) {
    state.page = context.pages().find((p) => p.url() === 'about:blank') || (await context.newPage())
  }
  await state.page.goto(CFG.url, { waitUntil: 'domcontentloaded', timeout: 40000 })
  await state.page.waitForTimeout(2500)
  // A dead session redirects to connect.visma.com, which detaches the tab from
  // playwriter, so "still on tripletex.no" is itself part of the signal.
  if (state.page.url().includes('tripletex.no')) {
    const title = (await state.page.title()).toLowerCase()
    if (title.includes('nedsoversikt')) verdict = 'live'
  }
} catch (e) {
  verdict = 'login'
}
console.log('VERDICT=' + verdict)
JS
}

# months_between YYYY-MM YYYY-MM: signed month delta (second minus first).
months_between() {
  local ay="${1%-*}" am="${1#*-}" by="${2%-*}" bm="${2#*-}"
  echo $(( (10#$by * 12 + 10#$bm) - (10#$ay * 12 + 10#$am) ))
}

open_in_browser() {
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$1"
  open -a "$BROWSER_APP" "$1" >/dev/null 2>&1 || open_url "$1"
}

banner "Tripletex: sign in and show me my hours"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Browser and playwriter" 1
BROWSER_APP=""
for app in "Brave Browser" "Google Chrome" "Chromium"; do
  if [[ -d "/Applications/$app.app" ]]; then BROWSER_APP="$app"; break; fi
done
if [[ -z "$BROWSER_APP" ]]; then
  warn "No Brave/Chrome found in /Applications; playwriter needs one."
  exit 1
fi
say "Browser: $BROWSER_APP"
if ! pgrep -qf "$BROWSER_APP"; then
  say "Not running, starting it."
  open -a "$BROWSER_APP" >/dev/null 2>&1 || true
  sleep 3
fi
if ! command -v playwriter >/dev/null 2>&1; then
  warn "playwriter not installed. Fix: npm i -g playwriter@latest"
  exit 1
fi
TMPJS="$(mktemp -t tripletex-wizard)" || { warn "mktemp failed"; exit 1; }
PW_SESSION="$(playwriter session new 2>&1 | sed -n 's/^Session \([0-9][0-9]*\) created.*/\1/p' | tail -n1)" || true
if [[ -z "$PW_SESSION" ]]; then
  warn "playwriter could not attach to $BROWSER_APP."
  step "Open any tab in $BROWSER_APP, click the Playwriter extension icon, re-run."
  exit 1
fi
say "Playwriter session $PW_SESSION ready."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Tripletex session" 1
say "Checking whether you are still signed in..."
NEED_LOGIN=1
if check_session | grep -q 'VERDICT=live'; then
  NEED_LOGIN=0
  printf '  %s✓%s Already signed in, skipping the login step.\n' "$GREEN" "$RESET"
else
  note "No live session in this browser."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Sign in with Google" 1
if (( NEED_LOGIN == 0 )); then
  say "Nothing to do here."
else
  say "Tripletex signs in through Visma Connect, which offers a Google button."
  say "Trying to click it for you..."
  AUTO="$(run_js "{\"url\":\"$LOGIN_URL\"}" <<'JS'
let outcome = 'manual'
try {
  if (!state.page || state.page.isClosed()) state.page = await context.newPage()
  await state.page.goto(CFG.url, { waitUntil: 'domcontentloaded', timeout: 40000 })
  await state.page.waitForTimeout(3000)
  const google = state.page.locator('button:has-text("Google"), a:has-text("Google")').first()
  if (await google.count()) {
    await google.click()
    outcome = 'clicked'
  }
} catch (e) {
  // Expected: connect.visma.com detaches the tab from playwriter the moment it
  // loads, which surfaces here as "page closed". Hand off to the human.
  outcome = 'manual'
}
console.log('OUTCOME=' + outcome)
JS
)"
  if grep -q 'OUTCOME=clicked' <<<"$AUTO"; then
    printf '  %s✓%s Clicked the Google button for you.\n' "$GREEN" "$RESET"
  else
    note "Playwriter cannot drive connect.visma.com; the tab detaches as it loads."
    note "So the click is yours. It is the 2FA-protected part anyway."
  fi
  open_in_browser "$LOGIN_URL"
  step "Click the Google button on the Visma Connect page."
  step "Pick your @capraconsulting.no account, finish 2FA if asked."
  step "Wait until the page lands back on tripletex.no."
  pause "Signed in? Press Enter."
  until check_session | grep -q 'VERDICT=live'; do
    warn "Still no live session."
    confirm "Try again?" || { SKIPPED+=("Tripletex sign-in"); finish; exit 1; }
    open_in_browser "$LOGIN_URL"
    pause "Press Enter once you are back on tripletex.no."
  done
  printf '  %s✓%s Signed in.\n' "$GREEN" "$RESET"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Show $TARGET_MONTH" 0
DELTA="$(months_between "$(date +%Y-%m)" "$TARGET_MONTH")"
SHOT="${TMPDIR:-/tmp}/tripletex-$TARGET_MONTH.png"
say "Opening Månedsoversikt and stepping to ${TARGET_MONTH}..."
RESULT="$(run_js "{\"url\":\"$MONTH_URL\",\"delta\":$DELTA,\"shot\":\"$SHOT\"}" <<'JS'
if (!state.page || state.page.isClosed()) state.page = await context.newPage()
if (!state.page.url().includes('monthlyHourlist')) {
  await state.page.goto(CFG.url, { waitUntil: 'domcontentloaded', timeout: 40000 })
}
await state.page.waitForTimeout(2000)
// The page opens on the current month; a.previousPeriod / a.nextPeriod step by one.
const arrow = CFG.delta < 0 ? 'a.previousPeriod' : 'a.nextPeriod'
for (let i = 0; i < Math.abs(CFG.delta); i++) {
  await state.page.locator(arrow).first().click()
  await state.page.waitForTimeout(1800)
}
await state.page.setViewportSize({ width: 1600, height: 900 })
await state.page.waitForTimeout(1200)
const heading = await state.page.evaluate(() => {
  const el = Array.from(document.querySelectorAll('td,th,h1,h2')).find(
    (e) => e.innerText && e.innerText.indexOf('nedsoversikt -') > -1,
  )
  return el ? el.innerText.trim().split('\n')[0] : ''
})
const rows = await state.page.evaluate(() =>
  Array.from(document.querySelectorAll('tr'))
    .map((tr) =>
      Array.from(tr.querySelectorAll('td,th'))
        .map((c) => c.innerText.trim().replace(/\s+/g, ' '))
        .filter(Boolean),
    )
    // Every row whose second cell is a bare number is an activity or summary
    // total. Skips the per-day detail rows at the bottom (those lead with a
    // date) and the Feriesaldo block (values like "7d 0,0t").
    .filter(
      (r) =>
        r.length >= 2 &&
        r[0].length >= 3 &&
        /^[0-9]+([.,][0-9]+)?$/.test(r[1]) &&
        !/^[0-9]{4}-[0-9]{2}-[0-9]{2}/.test(r[0]),
    )
    .map((r) => r[0].slice(0, 78) + ' | ' + r[1]),
)
await state.page.screenshot({ path: CFG.shot, scale: 'css' })
await state.page.bringToFront()
console.log('HEADING=' + heading)
rows.forEach((r) => console.log('ROW=' + r))
JS
)"

HEADING="$(sed -n 's/^\[log\] HEADING=//p;s/^HEADING=//p' <<<"$RESULT" | tail -n1)"
MONTHS_NO=(januar februar mars april mai juni juli august september oktober november desember)
EXPECT="${MONTHS_NO[$(( 10#${TARGET_MONTH#*-} - 1 ))]} ${TARGET_MONTH%-*}"

printf '\n'
if [[ -n "$HEADING" ]]; then
  printf '  %s%s%s\n\n' "$BOLD" "$HEADING" "$RESET"
  if ! grep -qi "$EXPECT" <<<"$HEADING"; then
    warn "Expected $EXPECT, check the period selector on the page."
  fi
else
  warn "Could not read the month heading; look at the browser tab directly."
fi

sed -n 's/^\[log\] ROW=/  /p;s/^ROW=/  /p' <<<"$RESULT"
printf '\n'
[[ -f "$SHOT" ]] && note "screenshot: $SHOT"
say "The tab is open and focused in $BROWSER_APP. Go look."
open -a "$BROWSER_APP" >/dev/null 2>&1 || true

finish
